#!/bin/bash

source ${ZENOBIA_LIBEXEC_DIR}/functions.sh

TARGET_ARTIFACT_NAME=$1
EXECUTABLE_FILE_NAME=$2

JAVA_COMMAND=$(cat << 'EOS'
java -jar "$0" "$@"
exit $?
EOS
)

echo "${JAVA_COMMAND}" > ${ZENOBIA_BIN_DIR}/${EXECUTABLE_FILE_NAME}
cat ${ZENOBIA_BIN_DIR}/${TARGET_ARTIFACT_NAME} >> ${ZENOBIA_BIN_DIR}/${EXECUTABLE_FILE_NAME}

chmod a+x ${ZENOBIA_BIN_DIR}/${EXECUTABLE_FILE_NAME}
