#!/bin/bash

source ${ZENOBIA_LIBEXEC_DIR}/functions.sh

ACTUAL_ARTIFACT_DIR=$1
ACTUAL_ARTIFACT_NAME=$2
LINK_ARTIFACT_NAME=$3

if [ -e ${ZENOBIA_BIN_DIR}/${LINK_ARTIFACT_NAME} ]; then
    rm ${ZENOBIA_BIN_DIR}/${LINK_ARTIFACT_NAME} 2>&1 > /dev/null
fi

if [ ${RUN_CYGWIN} -eq 0 ]; then
    ln -s ${ACTUAL_ARTIFACT_DIR}/${ACTUAL_ARTIFACT_NAME} ${ZENOBIA_BIN_DIR}/${LINK_ARTIFACT_NAME}
else
    cp -p ${ACTUAL_ARTIFACT_DIR}/${ACTUAL_ARTIFACT_NAME} ${ZENOBIA_BIN_DIR}/${LINK_ARTIFACT_NAME}
fi

logging INFO "current active version ${ACTUAL_ARTIFACT_NAME}"
